In [21]:
import pandas as pd
import numpy as np

cols =  ['yr1','mn1','hr1','plev1','hlev1','tlev1','qlev1', 
          'yr2','mn2','hr2','plev2','hlev2','tlev2','qlev2', 
          'yr3','mn3','hr3','plev3','hlev3','tlev3','qlev3', 
          'yr4','mn4','hr4','plev4','hlev4','tlev4','qlev4', 
          'yr5','mn5','hr5','plev5','hlev5','tlev5','qlev5', 
          'yr6','mn6','hr6','plev6','hlev6','tlev6','qlev6', 
          'yr7','mn7','hr7','plev7','hlev7','tlev7','qlev7']

df = pd.read_csv('../examples/Sample_obs/Sample_profile.txt', header = None, names = cols)
df

,yr1,mn1,hr1,plev1,hlev1,tlev1,qlev1,yr2,mn2,hr2,...,hlev6,tlev6,qlev6,yr7,mn7,hr7,plev7,hlev7,tlev7,qlev7
0,2002,6,800,98100.0,317.0,285.6,0.008800,2002,6,1200,...,317.0,301.0,0.009421,2002,6,200,98100.0,317.0,290.6,0.010172
1,2002,6,800,97400.0,377.0,289.0,0.008922,2002,6,1200,...,326.0,299.4,0.008538,2002,6,200,97700.0,352.0,291.6,0.009255
2,2002,6,800,95300.0,562.0,290.4,0.009552,2002,6,1200,...,810.0,294.4,0.007892,2002,6,200,92500.0,816.0,288.8,0.008673
3,2002,6,800,94100.0,670.0,290.0,0.008024,2002,6,1200,...,1530.0,287.8,0.007189,2002,6,200,91700.0,889.0,288.6,0.008070
4,2002,6,800,92500.0,816.0,290.4,0.005994,2002,6,1200,...,1714.0,286.0,0.006949,2002,6,200,89800.0,1066.0,288.6,0.007191
5,2002,6,800,92100.0,852.0,290.6,0.006062,2002,6,1200,...,2021.0,285.8,0.004337,2002,6,200,85000.0,1527.0,284.8,0.008360
6,2002,6,800,88000.0,1237.0,287.2,0.007646,2002,6,1200,...,2534.0,282.2,0.002194,2002,6,200,83900.0,1640.0,284.0,0.008527
7,2002,6,800,85000.0,1528.0,286.0,0.005507,2002,6,1200,...,2645.0,284.4,0.001634,2002,6,200,82200.0,1810.0,284.4,0.008645
8,2002,6,800,83900.0,1640.0,285.0,0.005989,2002,6,1200,...,3149.0,281.2,0.001855,2002,6,200,70000.0,3132.0,278.2,0.005546
9,2002,6,800,77000.0,2352.0,282.2,0.003175,2002,6,1200,...,3248.0,280.6,0.001278,2002,6,200,66400.0,3570.0,275.6,0.004866
10,2002,6,800,73600.0,2723.0,280.2,0.005199,2002,6,1200,...,3501.0,281.4,0.000400,2002,6,200,56300.0,4884.0,268.9,0.001044
11,2002,6,800,70000.0,3133.0,278.8,0.004252,2002,6,1200,...,4185.0,276.0,0.000380,2002,6,200,55700.0,4968.0,268.5,0.001215
12,2002,6,800,67000.0,3496.0,277.0,0.003593,2002,6,1200,...,4725.0,274.4,0.000138,2002,6,200,53700.0,5254.0,266.3,0.001901
13,2002,6,800,66100.0,3606.0,277.6,0.000723,2002,6,1200,...,5856.0,265.5,0.000041,2002,6,200,50000.0,5807.0,262.9,0.000982
14,2002,6,800,64100.0,3855.0,277.4,0.000418,2002,6,1200,...,7152.0,255.5,0.000394,2002,6,200,43400.0,6882.0,254.7,0.000390
15,2002,6,800,59600.0,4440.0,272.3,0.000302,2002,6,1200,...,7550.0,252.5,0.000222,2002,6,200,40400.0,7413.0,252.3,0.000089
16,2002,6,800,55700.0,4976.0,269.3,0.001093,2002,6,1200,...,8120.0,247.7,0.000114,2002,6,200,40000.0,7486.0,251.7,0.000084
17,2002,6,800,54300.0,5176.0,268.3,0.000713,2002,6,1200,...,8459.0,245.7,0.000046,2002,6,200,38800.0,7714.0,250.1,0.000016
18,2002,6,800,53100.0,5351.0,268.5,0.000255,2002,6,1200,...,9606.0,236.5,0.000048,2002,6,200,37600.0,7943.0,248.3,0.000096
19,2002,6,800,50000.0,5820.0,264.3,0.000157,2002,6,1200,...,10765.0,226.9,0.000025,2002,6,200,33600.0,8751.0,242.9,0.000026
20,2002,6,800,46900.0,6321.0,259.7,0.000141,2002,6,1200,...,10844.0,226.7,0.000022,2002,6,200,30400.0,9452.0,236.1,0.000031
21,2002,6,800,40000.0,7512.0,252.1,0.000154,2002,6,1200,...,12299.0,217.3,0.000009,2002,6,200,30000.0,9543.0,235.7,0.000029
22,2002,6,800,39500.0,7603.0,251.7,0.000134,2002,6,1200,...,20339.0,213.3,0.000000,2002,6,200,25400.0,10667.0,227.1,0.000015

In [7]:
import ctp_hilow

ModuleNotFoundError: No module named 'ctp_hilow'

In [44]:
nlev_in=len(df)
tlev_in = df['tlev1'].values
tlev_in =  tlev_in.reshape((nlev_in, 1))

qlev_in = df['qlev1'].values
qlev_in =  qlev_in.reshape((nlev_in, 1)) 

plev_in = df['plev1'].values
plev_in =  plev_in.reshape((nlev_in, 1)) 

qlev_in = qlev_in.tolist()
qlev_in[0]

[0.0087998267]

In [46]:
tlev_in.transpose()

array([[285.6, 289. , 290.4, 290. , 290.4, 290.6, 287.2, 286. , 285. ,
        282.2, 280.2, 278.8, 277. , 277.6, 277.4, 272.3, 269.3, 268.3,
        268.5, 264.3, 259.7, 252.1, 251.7]])

In [47]:
 df['plev1'].values

array([98100., 97400., 95300., 94100., 92500., 92100., 88000., 85000.,
       83900., 77000., 73600., 70000., 67000., 66100., 64100., 59600.,
       55700., 54300., 53100., 50000., 46900., 40000., 39500.])

In [49]:
np.random.rand((1,10))

(10,)